import cv2 
import numpy as np
kernal_matrix = np.ones((5,5))
#print(kernal_matrix)
img = cv2.imread('C:\\Users\\Admin\\OneDrive\\Pictures\\Saved Pictures\\Picasa\\My Bestie\\Hansil_The_Billionaire\\Mymackenziefoy\\16.jpg')
img_small = cv2.resize(img,(0,0),fx=0.2,fy=0.2)
color_image = cv2.cvtColor(img_small,cv2.COLOR_BGR2GRAY)
gussian_img = cv2.GaussianBlur(img_small,(3,3),0)
img_canny = cv2.Canny(gussian_img,150,200)
img_dilation = cv2.dilate(img_canny,kernal_matrix,iterations=1)
img_erode = cv2.erode(img_dilation,kernal_matrix, cv2.BORDER_CONSTANT)
img_Median = cv2.medianBlur(img_small,5)
img_biletarel = cv2.bilateralFilter(img_small,5,7,7)
cv2.imshow("Gray",color_image)
cv2.imshow("Original",img_small)
cv2.imshow("Gussian_Blur",gussian_img)
cv2.imshow("Canny_Image",img_canny)
cv2.imshow("Image_Dialetion",img_dilation)
cv2.imshow("Image_Erode",img_erode)
cv2.imshow("Image_Median",img_Median)
cv2.imshow("Image_Biletaral",img_biletarel)
cv2.waitKey(0)