import turtle as t
trt = t.Turtle()
color=("red", "yellow", "White", "cyan", "pink","green", "Magenta","Blue","Purple")
screen = t.Screen()
screen.bgcolor("Black")
for i in range(1):
    trt.begin_fill()
    trt.color(color[i])
    trt.pensize(2)
    trt.left(50)
    trt.forward(133)
    trt.circle(50,200)
    trt.right(140)
    trt.circle(50,200)
    trt.forward(133)
    trt.end_fill()
    t.delay(10)
t.hideturtle()
t.exitonclick()